"""
Pydantic schemas for request/response validation
"""
from app.schemas.user import (
    UserCreate,
    UserUpdate,
    UserResponse,
    UserLogin,
    Token,
    TokenPayload,
    RefreshToken,
)
from app.schemas.account import (
    AccountCreate,
    AccountUpdate,
    AccountResponse,
    AccountListResponse,
    AccountSummary,
    AccountSyncRequest,
    AccountSyncResponse,
)
from app.schemas.transaction import (
    TransactionCreate,
    TransactionUpdate,
    TransactionResponse,
    TransactionFilters,
    TransactionListResponse,
    TransactionAnalytics,
    BulkCategorizeRequest,
    BulkCategorizeResponse,
    CategoryStatistics,
    SpendingInsights,
)
from app.schemas.conversation import (
    ConversationCreate,
    ConversationUpdate,
    ConversationResponse,
    ConversationWithMessages,
    ConversationListResponse,
    MessageCreate,
    MessageResponse,
    ChatMessage,
    ChatResponse,
    QuickAnalysisRequest,
    QuickAnalysisResponse,
)
from app.schemas.recommendation import (
    RecommendationCreate,
    RecommendationUpdate,
    RecommendationResponse,
    RecommendationListResponse,
    RecommendationSummary,
    AcceptRecommendationRequest,
    RejectRecommendationRequest,
    CompleteRecommendationRequest,
    GenerateRecommendationsRequest,
    GenerateRecommendationsResponse,
)
from app.schemas.document import (
    DocumentCreate,
    DocumentUpdate,
    DocumentResponse,
    DocumentListResponse,
    DocumentSummary,
    DocumentUploadResponse,
    ProcessDocumentRequest,
    ProcessDocumentResponse,
    DocumentAnalysisResult,
    DocumentFilters,
    BatchProcessRequest,
    BatchProcessResponse,
)
from app.schemas.simulation import (
    SimulationCreate,
    SimulationUpdate,
    SimulationResponse,
    SimulationListResponse,
    SimulationSummary,
    RunSimulationRequest,
    RunSimulationResponse,
    SimulationResults,
    RetirementSimulationParams,
    InvestmentSimulationParams,
    LoanPayoffSimulationParams,
    BudgetForecastParams,
    SavingsGoalParams,
)
from app.schemas.workflow import (
    WorkflowCreate,
    WorkflowUpdate,
    WorkflowResponse,
    WorkflowListResponse,
    WorkflowSummary,
    WorkflowExecutionResponse,
    WorkflowExecutionListResponse,
    ActivateWorkflowRequest,
    ActivateWorkflowResponse,
    ExecuteWorkflowRequest,
    ExecuteWorkflowResponse,
    WorkflowFilters,
    ExecutionFilters,
)

__all__ = [
    # User schemas
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserLogin",
    "Token",
    "TokenPayload",
    "RefreshToken",
    # Account schemas
    "AccountCreate",
    "AccountUpdate",
    "AccountResponse",
    "AccountListResponse",
    "AccountSummary",
    "AccountSyncRequest",
    "AccountSyncResponse",
    # Transaction schemas
    "TransactionCreate",
    "TransactionUpdate",
    "TransactionResponse",
    "TransactionFilters",
    "TransactionListResponse",
    "TransactionAnalytics",
    "BulkCategorizeRequest",
    "BulkCategorizeResponse",
    "CategoryStatistics",
    "SpendingInsights",
    # Conversation schemas
    "ConversationCreate",
    "ConversationUpdate",
    "ConversationResponse",
    "ConversationWithMessages",
    "ConversationListResponse",
    "MessageCreate",
    "MessageResponse",
    "ChatMessage",
    "ChatResponse",
    "QuickAnalysisRequest",
    "QuickAnalysisResponse",
    # Recommendation schemas
    "RecommendationCreate",
    "RecommendationUpdate",
    "RecommendationResponse",
    "RecommendationListResponse",
    "RecommendationSummary",
    "AcceptRecommendationRequest",
    "RejectRecommendationRequest",
    "CompleteRecommendationRequest",
    "GenerateRecommendationsRequest",
    # Document schemas
    "DocumentCreate",
    "DocumentUpdate",
    "DocumentResponse",
    "DocumentListResponse",
    "DocumentSummary",
    "DocumentUploadResponse",
    "ProcessDocumentRequest",
    "ProcessDocumentResponse",
    "DocumentAnalysisResult",
    "DocumentFilters",
    "BatchProcessRequest",
    "BatchProcessResponse",
    # Simulation schemas
    "SimulationCreate",
    "SimulationUpdate",
    "SimulationResponse",
    "SimulationListResponse",
    "SimulationSummary",
    "RunSimulationRequest",
    "RunSimulationResponse",
    "SimulationResults",
    "RetirementSimulationParams",
    "InvestmentSimulationParams",
    "LoanPayoffSimulationParams",
    "BudgetForecastParams",
    "SavingsGoalParams",
    # Workflow schemas
    "WorkflowCreate",
    "WorkflowUpdate",
    "WorkflowResponse",
    "WorkflowListResponse",
    "WorkflowSummary",
    "WorkflowExecutionResponse",
    "WorkflowExecutionListResponse",
    "ActivateWorkflowRequest",
    "ActivateWorkflowResponse",
    "ExecuteWorkflowRequest",
    "ExecuteWorkflowResponse",
    "WorkflowFilters",
    "ExecutionFilters",
    "GenerateRecommendationsResponse",
]

# Made with Bob
